### ISSUE TITLE
Archive not merged with rest of case

### ISSUE THREAD

**Issue by roysmith** [GeneralNotability/spihelper#24]
I merged  Wikipedia:Sockpuppet investigations/RejsHajredini95 into Wikipedia:Sockpuppet investigations/Rejs12345, but the [archive](https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/RejsHajredini95/Archive) didn't get merged.  I'm reasonably sure I selected "All sections", and when it asked to confirm doing a histmerge, I did.

**Comment by roysmith** [comment]
I see it also duplicated the {{priorcases}} template, [in this edit.](https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/Rejs12345&diff=next&oldid=999546028&diffmode=source)

**Comment by GeneralNotability** [comment]
I'm actually not sure what is happening behind the scenes on the mediawiki side...I'm not doing a delete-merge-restore on the archive like I am on the main page, just a move (with subpages). I'll need to rework the merge functionality to handle the archive and pray that nobody ever tries to merge cases where we have multiple archives. This will be kind of messy, we'll need to copy with attribution rather than histmerging.

**Comment by GeneralNotability** [comment]
Released in 2.4.0.
