### ISSUE TITLE
badvalue error when editing SPI pages

### ISSUE THREAD

**Issue by Callanecc** [GeneralNotability/spihelper#35]
When I try to use the script to edit SPI pages I get a badvalue error (see screenshot below). Using different options (note/comment, close case, etc) still results in the same error.

![image](https://user-images.githubusercontent.com/4569718/114258124-c249d800-9a07-11eb-8c76-2994803c5ca5.png)

**Comment by Dreamy-Jazz** [comment]
Based on https://doc.wikimedia.org/mediawiki-core/master/php/classWikimedia_1_1ParamValidator_1_1TypeDef_1_1EnumDef.html#a29edaa7dd2492df3fea57e9a06e829fe badvalue seems to be an error passed back when the API fails. The explanation is "'badvalue': The value is not a recognized value. No data." My understanding is that this is raised when the enumeration type passed to the API was not recognised by the server. This means that the error is due to the request to the API in spiHelper_editPage had some invalid parameters. I'm not sure what they could be yet.

**Comment by Callanecc** [comment]
That did it. Thank you!
