### ISSUE TITLE
Extra "All comments go ABOVE this line, please" added

### ISSUE THREAD

**Issue by roysmith** [GeneralNotability/spihelper#48]
See https://en.wikipedia.org/w/index.php?title=Wikipedia:Sockpuppet_investigations/Alluburam&diff=prev&oldid=1031590673&diffmode=source

**Comment by Dreamy-Jazz** [comment]
This is likely due to the script checking for the existence of the horizontal line and not the comment. Perhaps the script should remove other uses of the comment. Not sure that someone would use this exact wording in a comment unless it was with the horizontal line, so perhaps removing isn't a bad idea.
