### ISSUE TITLE
CU Templates menu duplicated

### ISSUE THREAD

**Issue by roysmith** [GeneralNotability/spihelper#74]
Check out this screenshot.

<img width="475" alt="Screen Shot 2021-11-15 at 10 04 24 AM" src="https://user-images.githubusercontent.com/704337/141880971-1b7437f8-78df-4e4d-8794-aa56d3718329.png">

**Comment by Dreamy-Jazz** [comment]
@roysmith has this happened since?

The only way I could see this being caused by an issue with the script is if spiHelperGenerateSelect is run twice with the CU options. spiHelperGenerateSelect is only called once and is called inside the function spiHelperGenerateForm.

I guess that if this is related to the script and is not a browser bug, then spiHelperGenerateForm was called twice (by the "Continue" button from the top menu being hit twice. This function can be run twice due to it being async.

To address this perhaps the code could limit the calls to the function to at maximum once by some method that means the button can't be pressed again until the function has completed?

**Comment by Dreamy-Jazz** [comment]
To update I have confirmed this is caused by the double press of the button before the form has had a chance to update. By disabling the button quickly this should address the issue. Will submit a patch for this.

**Comment by roysmith** [comment]
Regarding, "has this happened since?", I don't believe I've ever seen it other than the one instance I described in this report.  So I guess the time window is pretty small.
