### ISSUE TITLE
Uncheckable checkbox for glocks

### ISSUE THREAD

**Issue by roysmith** [GeneralNotability/spihelper#91]
This is https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/FrancoHarrisJr.

I'm not sure I can reproduce this, but I think what happened was I added a few rows to accommodate newly found socks (MahoPa00 being one of the new ones).  The Duration fields come up with arbitrary pre-fills.  In this case, it was "1 week".  That's a bug too, but it's easy to work around by just putting in a new value.

The more serious thing is that the Req Lock checkbox for that row is greyed-out, and I can't see any way to make it active.

<img width="1070" alt="Screen Shot 2022-01-22 at 5 43 05 PM" src="https://user-images.githubusercontent.com/704337/150657766-dee3cd46-fc8e-4cc0-b3cf-6e9b6b45f589.png">

**Comment by roysmith** [comment]
Actually, I was able to work around it by adding another new row and putting MahoPa00 there.  But still a bug :-)

**Comment by Dreamy-Jazz** [comment]
@roysmith did the prefill of 1 week only happen for the row with the disabled "request lock" checkbox?

The pre-fills being 1 week and the checkbox being disabled means that `mw.util.isIPAddress(name, true)` returned true (i.e. the name is an IP address). If you add a blank line the name provided to the `spiHelperGenerateBlockTableLine` function is just the empty string. This is then passed to the mw.util function. I cannot preproduce this error, but this may be difference in browsers and browser version?

Obviously as this has happened, it is possible it could happen in the future (even if spihelper isn't to blame). As such a small fix that could be done is that once text is added /changed in the input that particular row has it's options updated. This would ensure that any rows updated to be IP addresses or changed to accounts would have the appropriate settings available.

Alternatively code could be written to file global locks, so that the checkbox does not need to be disabled at all (and thus this bug won't cause issues that cannot be resolved easily and without technical knowledge in inspecting element by the user).

**Comment by Dreamy-Jazz** [comment]
The patch above partially addresses this by allowing the global lock checkbox to change state on change of the username field. Maybe also checking for an empty string might be an idea?
